# Generated by Django 5.0.2 on 2024-03-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bol_number', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=200)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=200)),
                ('bol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.billoflading')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
    ]
